### ISSUE TITLE
python 3

### ISSUE THREAD

**Issue by transfluxus** [plecto/motorway#14]
does this run in py3.
i'm running the web_only example and get a 
```
Traceback (most recent call last):
  File "/Users/git/NLP/examples/motorway/web_only.py", line 2, in <module>
    from motorway.pipeline import Pipeline
  File "/Users/Documents/workspaces/VENVS/nlp/lib/python3.5/site-packages/motorway/pipeline.py", line 6, in <module>
    from motorway.connection import ConnectionIntersection
  File "/Users/Documents/workspaces/VENVS/nlp/lib/python3.5/site-packages/motorway/connection.py", line 6, in <module>
    from motorway.intersection import Intersection
  File "/Users/Documents/workspaces/VENVS/nlp/lib/python3.5/site-packages/motorway/intersection.py", line 2, in <module>
    from Queue import Empty
ImportError: No module named 'Queue'
~~~

**Comment by KristianOellegaard** [comment]
It's supposed to :-) what version of python 3?

**Comment by transfluxus** [comment]
2.5.2
there is a queue class in python 3.
I transormed the whole module with 2to3 but afterwards end at
```
Exception in thread connection_thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Documents/workspaces/VENVS/nlp/lib/python3.5/site-packages/motorway/mixins.py", line 94, in connection_thread
    refresh_connection_sock.connect(refresh_connection_stream)
  File "socket.pyx", line 471, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:4264)
zmq.error.ZMQError: Invalid argument
```

**Comment by SuneKjaergaard** [comment]
Closing this old issue. Motorway has been ported to Python3 by now :-)
